-- AlterTable
ALTER TABLE `donation` ADD COLUMN `timeCreated` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `payout` ADD COLUMN `timecreated` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- CreateTable
CREATE TABLE `Milestones` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `target` INTEGER NOT NULL,
    `current` INTEGER NOT NULL DEFAULT 0,
    `userId` INTEGER NOT NULL,
    `description` TEXT NOT NULL,
    `timecreated` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Milestones` ADD CONSTRAINT `Milestones_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
